// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Meal struct {
	ID          string         `json:"id"`
	MealPlanID  string         `json:"meal_plan_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Day         string         `json:"day"`
	MealType    string         `json:"meal_type"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type MealPlan struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedBy   string         `json:"created_by"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type MealPlanAccess struct {
	ID         string `json:"id"`
	UserID     string `json:"user_id"`
	MealPlanID string `json:"meal_plan_id"`
	Role       string `json:"role"`
}

type ShareLink struct {
	ID         string       `json:"id"`
	MealPlanID string       `json:"meal_plan_id"`
	CreatedBy  string       `json:"created_by"`
	Role       string       `json:"role"`
	ExpiresAt  time.Time    `json:"expires_at"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

type User struct {
	ID        string         `json:"id"`
	Email     string         `json:"email"`
	Name      string         `json:"name"`
	Picture   sql.NullString `json:"picture"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}
